Part A of Lab 2

In [20]:
import pandas as pd
import numpy as numpy
from matplotlib import pyplot as plt

In [21]:
#importing the csv then shwoing basic information
df = pd.read_csv('M2 - NBA - nba.csv')
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235,Marquette,6796117.0
2,John Holland,Boston Celtics,30,SG,27,6-5,205,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28,SG,22,6-5,185,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8,PF,29,6-10,231,NaN,5000000.0

In [22]:
#cleaning the null values from the data
newDf = df.fillna(0)
newDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    int64
 3   Position  457 non-null    object
 4   Age       457 non-null    int64
 5   Height    457 non-null    object
 6   Weight    457 non-null    int64
 7   College   457 non-null    object
 8   Salary    457 non-null    float64
dtypes: float64(1), int64(3), object(5)
memory usage: 32.3+ KB

In [23]:
#checking that all nnull values are gone
newDf.isna().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [24]:
newDf.describe()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.570000e+02
mean    17.678337   26.938731  221.522976  4.726121e+06
std     15.966090    4.404016   26.368343  5.218945e+06
min      0.000000   19.000000  161.000000  0.000000e+00
25%      5.000000   24.000000  200.000000  1.000000e+06
50%     13.000000   26.000000  220.000000  2.658240e+06
75%     25.000000   30.000000  240.000000  6.331404e+06
max     99.000000   40.000000  307.000000  2.500000e+07